INSERT INTO COURSE (COURSE_ID, COURSE_NAME) VALUES (1001 , 'Cloud');
INSERT INTO COURSE (COURSE_ID, COURSE_NAME) VALUES (1002 , 'Java');
INSERT INTO COURSE (COURSE_ID, COURSE_NAME) VALUES (1003 , '.Net');
INSERT INTO COURSE (COURSE_ID, COURSE_NAME) VALUES (1004 , 'ReactJS');
INSERT INTO COURSE (COURSE_ID, COURSE_NAME) VALUES (1005 , 'Python');